import Head from 'next/head'
import Header from "components/Header";
import HeroSection from "../components/HeroSection";
import Wave1 from "../components/Wave1";
import TechSection from "../components/TechSection";
import Blob1 from "../components/Blob1";
import SkillCards from "../components/SkillCards";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Chirag Bhalotia</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Header/>
                <HeroSection />
                <TechSection/>
                <SkillCards/>
                <Wave1/>
                <Blob1/>
            </main>
        </div>
    )
}
